### ISSUE TITLE
Add an option to display on not the private and test incidents with a Backstage permissions.

### ISSUE THREAD

**Issue by chussenot** [incident-io/backstage-plugins#21]
Hi, will be nice to allow the filtering of incidents with permission policies, https://backstage.io/docs/permissions/writing-a-policy/.
https://github.com/incident-io/backstage-plugins/blob/master/incident/src/components/HomePageIncidentCard/Content.tsx#L45

We want to keep private incidents private... and do not display them on the Homepage.

**Comment by samstarling** [comment]
Hey @chussenot, thanks for raising this. Private incidents will only display in Backstage if you're using an API key that has the permissiont to view private incident data. We'd strongly recommend against using an API key that has these permissions with Backstage. You should create an API key specifically for this use, which only has the "Can view data, like public incidents and organisation settings" permission. With this setup, you won't see any private incidents in Backstage.

I think that gets you what you need — given we don't have any current plans to integrate with Backstage policies, I'm going to close this issue, but thanks for the feedback!
